Rd 2883
reancloud/awesome_gem pull request #2
Opened 2021-03-03 11:07 UTC by Ivneetwahi

2021-03-03 16:09 UTC, lf12345 requested changes

2021-03-03 16:09 UTC, lf12345 commented on jenkins/release/Finish
> +  	if (env.mailAlert=="true")
Shouldn't it be ${env. mailAlert}?

2021-03-03 16:09 UTC, lf12345 commented on jenkins/release/Finish
> +  	    mail to: env.RECIPIENTS,
Shouldn't it be ${env. RECIPIENTS}?

2021-03-03 16:09 UTC, lf12345 commented on jenkins/hotfix/Build
> +@Library('reanplatform@RD-2883') _
Please remove the rean library branch since we aren't using it at the moment.

2021-03-03 16:09 UTC, lf12345 commented on lib/awesome_gem/version.rb
> +  VERSION = '1.30.0'
I think this version has been already released. You need to fix this. 
I see this error "!!! Already released version 1.30.0 to SCM.  You can go for publish to push to artifactory." in the Jenkins console log.

2021-03-04 06:32 UTC, Ivneetwahi commented on jenkins/release/Finish
> +  	    mail to: env.RECIPIENTS,
I tried this but didn't worked.

2021-03-04 06:32 UTC, Ivneetwahi commented on jenkins/release/Finish
> +  	if (env.mailAlert=="true")
Yes, changed.

2021-03-04 06:42 UTC, Ivneetwahi commented on jenkins/hotfix/Build
> +@Library('reanplatform@RD-2883') _
Removed branch

2021-03-04 06:42 UTC, Ivneetwahi commented on lib/awesome_gem/version.rb
> +  VERSION = '1.30.0'
Changed version

2021-03-09 08:44 UTC, closed without merging

2021-03-09 21:28 UTC, lf12345 requested changes

2021-03-09 21:28 UTC, lf12345 commented on jenkins/release/Build
> +  	if (env.mailAlert)
Please add a message saying we are sending out a failure email.

2021-03-09 21:28 UTC, lf12345 commented on jenkins/release/Finish
> +	    {
Please add a message saying we are sending out a failure email.

2021-03-09 21:28 UTC, lf12345 commented on jenkins/release/Start
> +	    {
Please add a message saying we are sending out a failure email.

2021-03-10 16:00 UTC, lf12345 approved these changes